---
auth_enabled: false

limits_config:
  allow_structured_metadata: true

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  compactor_address:  0.0.0.0
  instance_addr: localhost
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules  
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules

compactor:
  working_directory: /tmp/compactor

distributor:
  otlp_config:
    default_resource_attributes_as_index_labels:
      - "cloud.availability_zone"
      - "cloud.region"
      - "container.name"
      - "deployment.environment"
      - "k8s.cluster.name"
      - "k8s.container.name"
      - "k8s.cronjob.name"
      - "k8s.daemonset.name"
      - "k8s.deployment.name"
      - "k8s.job.name"
      - "k8s.namespace.name"
      - "k8s.node.name"
      - "k8s.pod.name"
      - "k8s.replicaset.name"
      - "k8s.statefulset.name"
      - "service.instance.id"
      - "service.name"
      - "service.namespace"