receivers:
  otlp: # doc. https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  
  filelog: # doc. https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/filelogreceiver/README.md
    poll_interval: "200ms"
    start_at: end
    include: [/etc/log/*/*.log]
    operators:
      - type: json_parser
        parse_from: body
  
  prometheus: # doc. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver
    config:
      scrape_configs:
      - job_name: otel-collector-metrics
        scrape_interval: 30s
        static_configs:
        - targets: ['127.0.0.1:8888']

processors:
  batch: # doc. https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor
    send_batch_size: 100
    timeout: 5s
  memory_limiter:
    check_interval: 5s
    limit_percentage: 75

  resourcedetection/system: # doc. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourceprocessor
    detectors: [ "system", docker ]
    system:
      hostname_sources: [ "os" ]
  
  resource: # doc. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourceprocessor
    attributes:
      - key: service.name
        value: logs-otel-collector
        action: insert

exporters:
  otlp: # doc. https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlpexporter
    endpoint: tempo:4317
    tls:
      insecure: true
  
  prometheusremotewrite: # doc. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter
    endpoint: http://mimir:9009/api/v1/push
    resource_to_telemetry_conversion:
      enabled: true # Convert resource attributes to metric labels

  otlphttp: # doc. https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlphttpexporter
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

extensions: # doc. https://github.com/open-telemetry/opentelemetry-collector/tree/main/extension
  health_check:
  pprof:
  zpages:

service:
  extensions: [ pprof, zpages, health_check ]
  # Doc. https://opentelemetry.io/docs/collector/internal-telemetry/
  telemetry:
    metrics:
      address: 127.0.0.1:8888
      level: detailed
    logs:
      level: DEBUG
      encoding: json
      processors:
        - batch:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: http://otelcollector:4318
    traces:
      processors:
        - batch:
            exporter:
              otlp:
                protocol: grpc/protobuf
                endpoint: http://otelcollector:4317
  pipelines:
    logs:
      receivers: [ otlp, filelog ]
      processors: [ memory_limiter, resource, resourcedetection/system, batch ]
      exporters: [ otlphttp ]
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, resourcedetection/system, batch ]
      exporters: [ otlp ]
    metrics:
      receivers: [ otlp, prometheus ]
      processors: [ memory_limiter, resourcedetection/system, batch ]
      exporters: [ prometheusremotewrite ]
