"""Initial migration

Revision ID: 0983ee289c8e
Revises: 
Create Date: 2025-01-27 14:51:15.242901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0983ee289c8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamada_regular',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('co_ies', sa.Integer(), nullable=True),
    sa.Column('no_ies', sa.String(), nullable=True),
    sa.Column('sg_ies', sa.String(), nullable=True),
    sa.Column('sg_uf_ies', sa.String(), nullable=True),
    sa.Column('no_campus', sa.String(), nullable=True),
    sa.Column('co_ies_curso', sa.Integer(), nullable=True),
    sa.Column('no_curso', sa.String(), nullable=True),
    sa.Column('ds_turno', sa.String(), nullable=True),
    sa.Column('ds_formacao', sa.String(), nullable=True),
    sa.Column('qt_vagas_concorrencia', sa.Integer(), nullable=True),
    sa.Column('co_inscricao_enem', sa.String(), nullable=True),
    sa.Column('no_inscrito', sa.String(), nullable=True),
    sa.Column('no_modalidade_concorrencia', sa.String(), nullable=True),
    sa.Column('st_bonus_perc', sa.Boolean(), nullable=True),
    sa.Column('qt_bonus_perc', sa.Float(), nullable=True),
    sa.Column('no_acao_afirmativa_bonus', sa.String(), nullable=True),
    sa.Column('nu_nota_candidato', sa.Float(), nullable=True),
    sa.Column('nu_notacorte_concorrida', sa.Float(), nullable=True),
    sa.Column('nu_classificacao', sa.Integer(), nullable=True),
    sa.Column('ensino_medio', sa.Boolean(), nullable=True),
    sa.Column('quilombola', sa.Boolean(), nullable=True),
    sa.Column('deficiente', sa.Boolean(), nullable=True),
    sa.Column('tipo_concorrencia', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chamada_regular')
    # ### end Alembic commands ###
